#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${GTFS_DB_USER} WITH ENCRYPTED PASSWORD '${GTFS_DB_PASSWORD}';
    CREATE DATABASE ${GTFS_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${GTFS_DB} TO ${GTFS_DB_USER};
EOSQL
